name: Upload Coverage to Coveralls

on:
  push:
    branches:
      - main

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls GitHub Action
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          #cd (혹시 빌드하는 repo가 root가 아니면 cd 명령어를 통해 이동해주자.)
          ./gradlew clean test jacocoTestReport coveralls
