name: Upload Coverage to Coveralls

on:
  push:
    branches:
      - main

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/setup-gradle@v1
        with:
          gradle-version: '7.2' # 사용하는 Gradle 버전으로 변경하세요
      
      - name: Build and run tests
        run: ./gradlew clean test
      
      - name: Generate coverage report
        run: ./gradlew jacocoTestReport
      
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./build/reports/jacoco/test/lcov.info # 생성된 커버리지 보고서의 경로로 변경하세요
