name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/setup-gradle@v1
        with:
          gradle-version: '7.2' # Gradle 버전을 맞게 설정해주세요
      
      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build

  coveralls:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Set execute permission for Gradle Wrapper
        run: chmod +x ./gradlew
      
      - name: Coveralls GitHub Action
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: 
          # 빌드하는 repo가 root가 아니면 해당 경로로 이동해줍니다.
          # cd (빌드하는 repo의 경로)
          ./gradlew clean test jacocoTestReport coveralls
